### ISSUE TITLE
'java.lang.NullPointerException' when using @TLS

### ISSUE THREAD

**Issue by ymmihw** [jbachorik/btrace#129]
trace source
	@TLS
	private static String name;

	@OnMethod(clazz = "java.io.FileInputStream", method = "<init>")
	public static void onNewFileInputStream(File f) {
		String str = Strings.str(f);
		name = str;
	}

log
java.lang.NullPointerException
	at java.io.FileInputStream.$btrace$com$ymmihw$btrace$helloworld$FileTracker$1$onNewFileInputStreamReturn(FileInputStream.java)
	at java.io.FileInputStream.<init>(FileInputStream.java:139)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.ymmihw.btrace.helloworld.FileTrackerTarget.main(FileTrackerTarget.java:13)

**Comment by jbachorik** [comment]
Caused by a regression in the TLS initialization generating code.

As a workaround you can initialize the @TLS annotated field to a value - that will prevent the NPE from occurring.
