### ISSUE TITLE
Btrace 1.3.1 doesn't support jdk6

### ISSUE THREAD

**Issue by DerekYangYC** [jbachorik/btrace#138]
Here is the output:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/sun/btrace/client/Main : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: com.sun.btrace.client.Main.  Program will exit.
```

**Comment by jbachorik** [comment]
Are you sure you need to run on such an ancient platform?
JDK 7 has already been EOLed (in April 2015) so moving to JDK 7 does not seem in any way premature :)

**Comment by jbachorik** [comment]
I'm going to close this issue. The annotation processors in JDK 7 were extremely improved over what was available in JDK 6 and this will allow BTrace to put some more advanced features to compiler/verifier. I don't want to hold back this kind of features just to keep backward compatibility with a dead platform.

If you really need JDK 6 compatibility you can branch/fork, update the _sourceCompatibility_ and _targetCompatibility_ values in __build.gradle__ file, and fix the sources where Java 7 language features are used. In _release-1.3_ branch there are no JDK 7 specific features in compiler/verifier so it still can be done pretty easily.

**Comment by DerekYangYC** [comment]
Thanks for the hints. Personally, I'd like to move to jdk7 or even 8 but it's a big and legacy system, not an easy job to upgrade jdk :)

**Comment by jbachorik** [comment]
I hope it is not a sensitive system :) The lack of security updates for decommissioned JDK 6 could be rather dangerous.
