### ISSUE TITLE
the swing program is rising an exception when using btrace

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#149]
the btrace contains the following code with int the class
@OnMethod(clazz="/.*/". method="/.*/")
public static void methodname(@Self Objec obj, @ProbeClassName String obj1, @ProbeMethodName String obj2)
{
        println(obj1);
        println(obj2);
}

are we not supposed to use the "/.*/" for the clazz in OnMethod, as i was trying to access all the classes which are running in my application or program.

**Comment by jbachorik** [comment]
First of all, you need to provide the exact exception you are getting.
Preferably with the associated stack trace.

Second of all, while you can do this it is not very advisable. In theory it
should work fine but since you are retransforming a large number of
classes, among them many of the core java classes, there is a lot of space
for something to go wrong.

**Comment by jbachorik** [comment]
Can't really do anything about it until you provide the exception stacktrace.
Please, reopen once the stacktrace is available.

**Comment by AbhishekPuligundla** [comment]
sorry for the late reply but it is the error I am getting while using the above mentioned format.

java.lang.ExceptionInInitializerError
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
	at java.util.Collections$EmptyIterator.<init>(Collections.java:4184)
	at java.util.Collections$EmptyIterator.<clinit>(Collections.java:4185)
	at java.util.Collections.emptyIterator(Collections.java:4181)
	at java.util.Collections$EmptySet.iterator(Collections.java:4314)
	at java.lang.Class.createAnnotationData(Class.java:3527)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
	at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
	at com.sun.btrace.agent.Main$2.run(Main.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.util.Locale.toLanguageTag(Locale.java:1416)
	at sun.util.locale.provider.LocaleProviderAdapter.isSupportedLocale(LocaleProviderAdapter.java:310)
	at sun.util.locale.provider.DateFormatSymbolsProviderImpl.isSupportedLocale(DateFormatSymbolsProviderImpl.java:63)
	at sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:286)
	at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:254)
	at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:357)
	at java.text.DateFormatSymbols.getInstanceRef(DateFormatSymbols.java:349)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:603)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
	at com.sun.btrace.comm.MessageCommand.<clinit>(MessageCommand.java:36)
	... 23 more
java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
	at java.lang.invoke.MethodHandleImpl$1.<init>(MethodHandleImpl.java:54)
	at java.lang.invoke.MethodHandleImpl.<clinit>(MethodHandleImpl.java:54)
	at java.lang.invoke.MethodHandle.<clinit>(MethodHandle.java:422)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
	at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.invoke.MethodHandleImpl.<clinit>(MethodHandleImpl.java:54)
	at java.lang.invoke.MethodHandle.<clinit>(MethodHandle.java:422)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
	at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java)
	at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.invoke.MethodHandleImpl.<clinit>(MethodHandleImpl.java:54)
	at java.lang.invoke.MethodHandle.<clinit>(MethodHandle.java:422)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
	at java.util.Collections$EmptyIterator.hasNext(Collections.java)
	at java.lang.Class.createAnnotationData(Class.java:3527)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
	at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
	at com.sun.btrace.agent.Main$2.run(Main.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
	at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
	at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
	at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
	at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
	at java.util.Collections$EmptyIterator.hasNext(Collections.java)
	at java.lang.Class.createAnnotationData(Class.java:3527)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
	at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
	at com.sun.btrace.agent.Main$2.run(Main.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
