### ISSUE TITLE
Tracing all methods of all available classes can make BTrace crash

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#154]
Sorry for the late reply, the error is like below when I use the  btrace code 
@OnMethod(clazz="/.*/", method="/.*/")
public static mehtod1()
{
}

Error:

java.lang.ExceptionInInitializerError
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
 at java.util.Collections$EmptyIterator.(Collections.java:4184)
 at java.util.Collections$EmptyIterator.(Collections.java:4185)
 at java.util.Collections.emptyIterator(Collections.java:4181)
 at java.util.Collections$EmptySet.iterator(Collections.java:4314)
 at java.lang.Class.createAnnotationData(Class.java:3527)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.createAnnotationData(Class.java:3526)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.createAnnotationData(Class.java:3526)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.getAnnotation(Class.java:3415)
 at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
 at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
 at com.sun.btrace.agent.Main$2.run(Main.java:369)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.NullPointerException
 at java.util.Locale.toLanguageTag(Locale.java:1416)
 at sun.util.locale.provider.LocaleProviderAdapter.isSupportedLocale(LocaleProviderAdapter.java:310)
 at sun.util.locale.provider.DateFormatSymbolsProviderImpl.isSupportedLocale(DateFormatSymbolsProviderImpl.java:63)
 at sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:286)
 at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:254)
 at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:357)
 at java.text.DateFormatSymbols.getInstanceRef(DateFormatSymbols.java:349)
 at java.text.SimpleDateFormat.(SimpleDateFormat.java:603)
 at java.text.SimpleDateFormat.(SimpleDateFormat.java:580)
 at com.sun.btrace.comm.MessageCommand.(MessageCommand.java:36)
 ... 23 more
 java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
 at java.lang.invoke.MethodHandleImpl$1.(MethodHandleImpl.java:54)
 at java.lang.invoke.MethodHandleImpl.(MethodHandleImpl.java:54)
 at java.lang.invoke.MethodHandle.(MethodHandle.java:422)
 java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
 at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.lang.invoke.MethodHandleImpl.(MethodHandleImpl.java:54)
 at java.lang.invoke.MethodHandle.(MethodHandle.java:422)
 java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.lang.invoke.MethodHandleImpl$1.$btrace$traceclock$anadigiMethod(MethodHandleImpl.java:46)
 at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java)
 at java.lang.invoke.MethodHandleImpl$1.run(MethodHandleImpl.java:54)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.lang.invoke.MethodHandleImpl.(MethodHandleImpl.java:54)
 at java.lang.invoke.MethodHandle.(MethodHandle.java:422)
 java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
 at java.util.Collections$EmptyIterator.hasNext(Collections.java)
 at java.lang.Class.createAnnotationData(Class.java:3527)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.createAnnotationData(Class.java:3526)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.createAnnotationData(Class.java:3526)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.getAnnotation(Class.java:3415)
 at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
 at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
 at com.sun.btrace.agent.Main$2.run(Main.java:369)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 java.lang.NoClassDefFoundError: Could not initialize class com.sun.btrace.comm.MessageCommand
 at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:1699)
 at com.sun.btrace.BTraceRuntime.println(BTraceRuntime.java:1196)
 at com.sun.btrace.BTraceUtils.println(BTraceUtils.java:1220)
 at java.util.Collections$EmptyIterator.$btrace$traceclock$anadigiMethod(Collections.java:46)
 at java.util.Collections$EmptyIterator.hasNext(Collections.java)
 at java.lang.Class.createAnnotationData(Class.java:3527)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.createAnnotationData(Class.java:3526)
 at java.lang.Class.annotationData(Class.java:3510)
 at java.lang.Class.getAnnotation(Class.java:3415)
 at com.sun.btrace.runtime.ClassFilter.isCandidate(ClassFilter.java:84)
 at com.sun.btrace.agent.Client.isCandidate(Client.java:262)
 at com.sun.btrace.agent.Main$2.run(Main.java:369)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by jbachorik** [comment]
Ok. This seems to be caused by instrumenting classes required during BTrace startup.

**Comment by AbhishekPuligundla** [comment]
so what should i do, if i remove the above statement it works fine, but i want to trace all the files that exist within a package or a program or a jar file. how can i trace all class with in a singale package name with out using the statement @OnMethod(clazz="/.*/",method="/.*/").

**Comment by jbachorik** [comment]
You will need to know the package names contained in the jar. With the
settings you are using you are tracing the whole JDK.

Once you know the package names you can do eg. `@OnMethod(clazz="/<regex to
match packages>/", method="/.*/")...`

**Comment by AbhishekPuligundla** [comment]
Say that i have three class in the package com.mypackages then how should i be able to trace each class when the object of those classes are created

**Comment by jbachorik** [comment]
This one is pretty easy - `@OnMethod(clazz="/com\\.mypackages\\.*/",
method="/.*/")` should do the trick
