### ISSUE TITLE
Problems with @Return parameter

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#174]
i am getting this error while tracing an application but the error is not displaying after i remove the Return parameter. why this error occurs and i do not understand what you explained in the #78 . Can you explain what it means briefly

**Comment by jbachorik** [comment]
It's extremely difficult to tell what is going wrong just from a very vague description. As I asked you several times, include the BTrace script causing this and, if possible, also the source of the class the instrumentation of which invokes this error.

**Comment by AbhishekPuligundla** [comment]
source class:


import java.io.*;
import java.util.HashMap;
public class trail7
{
		public static void main(String args[])
		{
			try{ Thread.sleep(10000); }catch(Exception e){}
				trail7 object1=new trail7();
				String hello="hello";
				int n=object1.trail7Method(hello);
		}
	int trail7Method(String he)
	{	
		//System.out.println(he);
		int m=698;
		return m;
	}
}

BtraceScript:
import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;
import com.sun.btrace.*;
import java.lang.reflect.Field;
@BTrace //(unsafe=true)
public class tracetrail7
{
	@OnMethod(clazz="trail7", method="/.*/", location=@Location(Kind.RETURN))
	public static void trail7Method3(@Return int data,  @Self Object obj, @ProbeClassName String classname, @ProbeMethodName String methodname)
	{
		println("method Return");
		println(classname);
		println(methodname);
		printFields(obj);
		println(data);
	}
	
}


if i am using the above script i am getting the below error

btrace DEBUG: java.lang.NullPointerException
java.lang.NullPointerException
        at java.lang.String.<init>(String.java:198)
        at com.sun.btrace.org.objectweb.asm.Type.getInternalName(Unknown Source)

        at com.sun.btrace.util.LocalVariablesSorter.newLocal(LocalVariablesSorte
r.java:262)
        at com.sun.btrace.runtime.Instrumentor$15.callAction(Instrumentor.java:1
088)
        at com.sun.btrace.runtime.Instrumentor$15.onMethodReturn(Instrumentor.ja
va:1134)
        at com.sun.btrace.runtime.MethodReturnInstrumentor.visitInsn(MethodRetur
nInstrumentor.java:61)
        at com.sun.btrace.org.objectweb.asm.MethodAdapter.visitInsn(Unknown Sour
ce)
        at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sun.btrace.runtime.InstrumentUtils.accept(InstrumentUtils.java:66
)
        at com.sun.btrace.runtime.InstrumentUtils.accept(InstrumentUtils.java:62
)
        at com.sun.btrace.agent.Client.instrument(Client.java:317)
        at com.sun.btrace.agent.Client.doTransform(Client.java:143)
        at com.sun.btrace.agent.Client.transform(Client.java:122)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:1
88)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java
:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)


if i changed the btrace script like this

import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;
import com.sun.btrace.*;
import java.lang.reflect.Field;
@BTrace //(unsafe=true)
public class tracetrail7
{
	@OnMethod(clazz="trail7", method="/.*/", location=@Location(Kind.RETURN))
	public static void trail7Method3(@Return int data,  @Return String data1, @Self Object obj, @ProbeClassName String classname, @ProbeMethodName String methodname)
	{
		println("method Return");
		println(classname);
		println(methodname);
		printFields(obj);
		println(data);
                println(data1);
	}
	
}

I am getting this error

Invalid @Return parameter. Expected 'V, received Ljava/lang/String;
Invalid @Return parameter. Expected 'I, received Ljava/lang/String;

Here it is showing that instead of void and integer its getting string
but
if i re-arrange the  @Return int data, @Return String data1 to @Return String data1, @Return int data it prints this

method Return
trail7
trail7Method
{}
698
hello


I don't understand why @Return String data1 is required and why it is getting the string "hello". 
Also why after rearranging the @Return arguments its allowing string for the void.

what if i  don't know what type of return value and how many values a method is returning then how to print the different values. do i have to mention every datatype returning by using @Return argument annotations.

**Comment by jbachorik** [comment]
There are two issues intermingled in this report:

1. Matching a @Return parameter for primitive types is broken - it is causing the shown NPE
2. The verifier is not clever enough to recognize the multiple declaration of @Return parameter - it will accept only the last parameter and all the previous parameters will behave as if unannotated - eg. accepting the calling parameters of the traced method.
