### ISSUE TITLE
BTrace is crashing the applications that is attached with

### ISSUE THREAD

**Issue by AbhishekPuligundla** [jbachorik/btrace#177]
Some how the btrace is able to crash the application when i started tracing the application. The applicaiton will be like in loading state continuosly or will show an internal error message at the applicaion window. If i stop tracing and restart the application, the applicaion works normally. the applicaion is crashing when ever i use btrace. Some times the crashing happens in the middle of the application usage also while using btrace.

**Comment by jbachorik** [comment]
Can't really make anything out from the description. What is the internal error, does it generate hs_err_* file? What is the script you are using? Which JDK is used?

If you see a VM crash it will most likely be a problem in JVM - unless you are using BTrace in unsafe mode. But until I get more information I really can't tell what is happening.

**Comment by AbhishekPuligundla** [comment]
1) The internal error is showing a message like "internal error has occured, if problem exists please contact your administrator" when using btrace.

2) The JDk i am using is 1.7.0_60
3) The script is not a complicated one it'll trace to check for method entries

@OnMethod(clazz="classname",method="/.*/",location=@Location(value=Kind.ENTRY))
public static void traceMethod(@Self Object obj, @ProbeClassName String clsname,@ProbeMethodName String methodname)
{
      println(strcat("class name is ",clsname));
      println(strcat("method name is ",methodname));
      printFields(obj);
}


4) I think there is no problem with jvm i was able to run other java programs at the same time which are not being traced and they are working fine.

5) hs_err_file is not generated

6) BTrace is in safe mode(not in unsafe mode)

**Comment by jbachorik** [comment]
This is weird - usually, when JVM dies with 'internal error has occurred ...' message the corresponding hs_err_* file should be generated. It would contain all the necessary information for diagnosing the crash.

If BTrace engine were to crash you would get the standard exception stacktrace in the app output.

Not much information to start with, unfortunately.

As the first step, try increasing the maximum perm size (-XX:MaxPermSize=200m) to rule out out-of-memory condition due to massive class retransformation.

**Comment by AbhishekPuligundla** [comment]
I am getting the following error 

Exception in thread "Thread-74" java.lang.NullPointerException
        at com.sun.btrace.BTraceRuntime$SpeculativeQueueManager.send(BTraceRuntime.java:302)
        at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:2097)
        at com.sun.btrace.BTraceRuntime.exitImpl(BTraceRuntime.java:2232)
        at com.sun.btrace.BTraceRuntime.handleExit(BTraceRuntime.java:475)
        at com.sun.btrace.agent.Main$2.run(Main.java:95)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-70" java.lang.NullPointerException
        at com.sun.btrace.BTraceRuntime$SpeculativeQueueManager.send(BTraceRuntime.java:302)
        at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:2097)
        at com.sun.btrace.BTraceRuntime.exitImpl(BTraceRuntime.java:2232)
        at com.sun.btrace.BTraceRuntime.handleExit(BTraceRuntime.java:475)
        at com.sun.btrace.agent.Main$2.run(Main.java:95)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-65" java.lang.NullPointerException
        at com.sun.btrace.BTraceRuntime$SpeculativeQueueManager.send(BTraceRuntime.java:302)
        at com.sun.btrace.BTraceRuntime.send(BTraceRuntime.java:2097)
        at com.sun.btrace.BTraceRuntime.exitImpl(BTraceRuntime.java:2232)
        at com.sun.btrace.BTraceRuntime.handleExit(BTraceRuntime.java:475)
        at com.sun.btrace.agent.Main$2.run(Main.java:95)
        at java.lang.Thread.run(Thread.java:745)

**Comment by AbhishekPuligundla** [comment]
i changed the size but the same error is comming. it's not related to memory.

**Comment by jbachorik** [comment]
Aren't you, by any chance, copying external tools.jar to your application (as you mentioned in a different issue)?

**Comment by AbhishekPuligundla** [comment]
Yes i am copying a external tools.jar to my application.

**Comment by jbachorik** [comment]
Ok, this might explain the crash. By copying over tools.jar from a different jar you are asking for troubles. This is not a supported scenario. You should better start your application on a full JDK instead of just JRE - in that case an appropriate tools.jar will be available.
