### ISSUE TITLE
AggregationFunction.QUANTIZE fails for values larger than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by webtrekk-kane** [jbachorik/btrace#190]
I was using the AggregationFunction.QUANTIZE for a execution performance histogram for which I am using the @Duration value. That in turn is a long and may get larger than Integer.MAX_VALUE.

As a result, I see the following when such large values appear:

```
java.lang.ArrayIndexOutOfBoundsException: 64
        at com.sun.btrace.aggregation.Quantize.add(Quantize.java:67)
        at com.sun.btrace.aggregation.Aggregation.add(Aggregation.java:88)
        at com.sun.btrace.BTraceRuntime.addToAggregation(BTraceRuntime.java:1794)
        at com.sun.btrace.BTraceUtils$Aggregations.addToAggregation(BTraceUtils.java:5042)
        at com.sun.btrace.BTraceUtils.addToAggregation(BTraceUtils.java:3209)
```

I just verified that beginning with value Integer.MAX_VALUE + 1, the function "getBucketIndex" returns 64.

**Comment by webtrekk-kane** [comment]
:+1: Very cool, thank you!
